### ISSUE TITLE
Memory leak when using useBlockNumber({watch: true}) -- creates a new websocket subscription on every block until it runs out of memory

### ISSUE THREAD

**Issue by acoutts** [wevm/wagmi#3656]
### Describe the bug

Consider a simple hook like this which consumes the block number for invalidation:

```typescript
export const useAccountData = () => {
  const queryClient = useQueryClient()
  const { address } = useAccount()
  const { data: blockNumber } = useBlockNumber({ chainId: activeChains.l2.id, watch: true })
  const {
    data: accountData,
    isLoading,
    queryKey,
  } = useReadContract({
    address: env.NEXT_PUBLIC_CONTRACT as `0x${string}`,
    abi: fooAbi,
    functionName: "fooFunction",
  })

  useEffect(() => {
    void queryClient.invalidateQueries({ queryKey })
  }, [blockNumber])

  return { accountData, isLoading }
}
```

When this is used just one time in the app and you look at the websocket traffic, on every single block event it's creating a new subscription and never closes the old ones. If you have 2 components consuming the hook, it will start 2 subscriptions with every block, etc for each consumer.

In the following screenshot notice it first gets 3 subscription responses, then starts a new one, then gets 4, etc. I ensured that hook above was only called/active one time, and setting `watch:false` resulted in no websocket activity.
<img width="1010" alt="Screenshot 2024-02-29 at 12 38 26 PM" src="https://github.com/wevm/wagmi/assets/9597207/ede29153-91e2-41be-8674-64057fba0143">

The result is you will run out of memory and the RPC will rate limit the client because eventually it has too many subscriptions.

I tested this with QuickNode and the following:
```json
"@web3modal/wagmi": "^4.0.11",
```

I tried the same pattern but in a context and it's the same issue. The problem seems to be wagmi just keeps making new subscriptions.

If I instead use viem to get the block number, it works fine and only starts one subscription, even if I have several parts of the app consuming this hook for the block number:

```typescript
export const useOnL2Block = () => {
  const [blockNumber, setBlockNumber] = useState(BigInt(0))

  const subscribe = useCallback(() => {
    return watchBlockNumber(config.getClient(), {
      onBlockNumber: (blockNumber) => {
        setBlockNumber(blockNumber)
      },
    })
  }, [])

  useEffect(() => {
    const unsubscribe = subscribe()

    return () => unsubscribe()
  }, [subscribe])

  return { blockNumber }
}

export const useAccountData = () => {
  const queryClient = useQueryClient()
  const { address } = useAccount()

  const { blockNumber } = useOnL2Block()

  // const { data: blockNumber } = useBlockNumber({ chainId: activeChains.l2.id, watch: watch })
  const {
    data: accountData,
    isLoading,
    queryKey,
  } = useReadContract({
    address: env.NEXT_PUBLIC_CONTRACT as `0x${string}`,
    abi: fooAbi,
    functionName: "fooFunction",
  })

  useEffect(() => {
    void queryClient.invalidateQueries({ queryKey })
  }, [blockNumber])

  return { accountData, isLoading }
}
```

<img width="1055" alt="Screenshot 2024-02-29 at 12 54 16 PM" src="https://github.com/wevm/wagmi/assets/9597207/904b8094-73d9-47fe-b402-828545f5daf1">

As another side note, what's the correct pattern to ensure there's only one bock subscription in the app so i'm not making unnecessary rpc requests?

### Wagmi Version

2.6.5

### Viem Version

2.7.16

### TypeScript Version

5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by wkyleg** [comment]
I'll take

**Comment by wkyleg** [comment]
So internally, `useBlockNumber` uses `useWatchBlockNumber` which uses WAGMI's `watchBlockNumber` in a `useEffect` hook. 

There is a note `// TODO: wrap in viem's `observe` to avoid duplicate invocations.` which could be relevant here. Inside this function the action `viem_watchBlockNumber` is being dispatched to viem.

I need to investigate a little bit further and test, but I believe that this might be fixed by setting `enabled` to be false in the value passed into `useWatchBlockNumber` inside `useBlockNumber`. The hook could also auto close its own web socket but I can see how this could cause other complications

**Comment by wkyleg** [comment]
I noticed that one of the test suites/dev sites was using the different function `getBlockNumber` which might be why this was not noticed in testing

**Comment by wkyleg** [comment]
I work on a branch with a fix

**Comment by wkyleg** [comment]
Is your View instance set to use polling by any chance @acoutts ?

Because Viem's `watchBlockNumber` is configured to use `observer` correctly, but the connection version with WebSocket is not. See https://github.com/wevm/viem/blob/main/src/actions/public/watchBlockNumber.ts

My best guess right now is that this is actually a Viem issue

**Comment by acoutts** [comment]
I'm only using websockets in this case, no polling.

**Comment by wkyleg** [comment]
You definitely don't see the a WebSocket being created using rpc `eth_blockNumber`?

It's strange to me that Viem would not be creating additional sockets the way it's configured right now

**Comment by acoutts** [comment]
No i'm not doing anything out of the ordinary. it's very easy to reproduce as i said in my original post

**Comment by Yuripetusko** [comment]
I tried this and also getting the same results. Trying to dig deeper now and so far couldn't pinpoint the cause, but will continue a bit more

**Comment by Yuripetusko** [comment]
So I was tinkering with this a bit, and I did manage to make the issue go away by patching `useWatchBlockNumber`, basically I think what helped the most was stringifying an object passed to useEffect hook (exhaustive dependency), otherwise this effect keeps re-rendering. But test is failing with my change and it's late here, i'll try to continue tomorrow

<img width="701" alt="image" src="https://github.com/wevm/wagmi/assets/666169/0970690a-3068-4ed1-8e7f-df36e9d45a50">

**Comment by Yuripetusko** [comment]
Basically the react's `Object.is` that is used to compare useEffect's previous values with new ones sees this object as not equal to the previous and re-runs useEffect again

**Comment by Yuripetusko** [comment]
@acoutts I created a PR with a potential fix, not super happy with amount of code I had to add, as i'm not familiar with codebase just yet, but if you could check out the branch and test that would be great

1. edit `playgrounds/next/src/wagmi.ts` to add wss transport. ie.
```
[sepolia.id]: webSocket('wss://eth-sepolia.api.onfinality.io/public-ws'),
```
2. add to `playgrounds/next/src/app/page.tsx`

```
const { data: blockNumber } = useBlockNumber({
    chainId: sepolia.id,
    watch: true,
  })

  console.log('blockNumber', blockNumber)
```

Launch with `pnpm dev:next` and check the network tab

**Comment by wkyleg** [comment]
I'll have a look

**Comment by Yuripetusko** [comment]
> // TODO: wrap in viem's observe to avoid duplicate invocations.

Oh I didn't notice this comment, will check what is this about, perhaps there's a cleaner way

**Comment by wkyleg** [comment]
@Yuripetusko @acoutts I just tested this branch with instructions above and I can confirm there is only 1 web socket being created. 

I don't see any easier way to handle this. Only kind of strange this is that when I print the result inside of use effect, it will print a function printed first, then `undefined`.
Given
```
  useEffect(() => {
    console.log('inside use effect')
    console.log(subscription.current)
    return () => {
      subscription.current?.()
      subscription.current = undefined
    }
  }, [])
```

I see this printed in the network console:

![image](https://github.com/wevm/wagmi/assets/16677991/e0bbd1e4-77e4-4749-82df-6fa1a532457a)


Are there any obvious edge cases we should be aware of here? Testing what happens when there are 2 subscriptions to `useWatchBlockNumber` seems like a good test case.

**Comment by wkyleg** [comment]
> > // TODO: wrap in viem's observe to avoid duplicate invocations.
> 
> Oh I didn't notice this comment, will check what is this about, perhaps there's a cleaner way

Yes, in theory Viem is supposed to manage all of this internally, if I understand correctly

**Comment by wkyleg** [comment]
For reference @Yuripetusko 
![image](https://github.com/wevm/wagmi/assets/16677991/f54b2bcc-2d99-4ffa-b8ca-3b96b032e181)

**Comment by Yuripetusko** [comment]
> @Yuripetusko @acoutts I just tested this branch with instructions above and I can confirm there is only 1 web socket being created.
> 
> I don't see any easier way to handle this. Only kind of strange this is that when I print the result inside of use effect, it will print a function printed first, then `undefined`. Given
> 
> ```
>   useEffect(() => {
>     console.log('inside use effect')
>     console.log(subscription.current)
>     return () => {
>       subscription.current?.()
>       subscription.current = undefined
>     }
>   }, [])
> ```
> 
> I see this printed in the network console:
> 
> ![image](https://private-user-images.githubusercontent.com/16677991/311846460-e0bbd1e4-77e4-4749-82df-6fa1a532457a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxODc5NDEsIm5iZiI6MTcxMDE4NzY0MSwicGF0aCI6Ii8xNjY3Nzk5MS8zMTE4NDY0NjAtZTBiYmQxZTQtNzdlNC00NzQ5LTgyZGYtNmZhMWE1MzI0NTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDIwMDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNTJmMjZiNDBjODgxNTM0MGYyNzIzYzIzNDQ1ZDkxNWFmNGYyNTNlZmU5MGY0NDA2OWE3NjcyODNhODk3OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FfqsMsp8__-XUFRdNgkVRblsigLS8kywu-_7WvCj-Ik)
> 
> Are there any obvious edge cases we should be aware of here? Testing what happens when there are 2 subscriptions to `useWatchBlockNumber` seems like a good test case.




> @Yuripetusko @acoutts I just tested this branch with instructions above and I can confirm there is only 1 web socket being created.
> 
> I don't see any easier way to handle this. Only kind of strange this is that when I print the result inside of use effect, it will print a function printed first, then `undefined`. Given
> 
> ```
>   useEffect(() => {
>     console.log('inside use effect')
>     console.log(subscription.current)
>     return () => {
>       subscription.current?.()
>       subscription.current = undefined
>     }
>   }, [])
> ```
> 
> I see this printed in the network console:
> 
> ![image](https://private-user-images.githubusercontent.com/16677991/311846460-e0bbd1e4-77e4-4749-82df-6fa1a532457a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxODc5NDEsIm5iZiI6MTcxMDE4NzY0MSwicGF0aCI6Ii8xNjY3Nzk5MS8zMTE4NDY0NjAtZTBiYmQxZTQtNzdlNC00NzQ5LTgyZGYtNmZhMWE1MzI0NTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDIwMDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNTJmMjZiNDBjODgxNTM0MGYyNzIzYzIzNDQ1ZDkxNWFmNGYyNTNlZmU5MGY0NDA2OWE3NjcyODNhODk3OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FfqsMsp8__-XUFRdNgkVRblsigLS8kywu-_7WvCj-Ik)
> 
> Are there any obvious edge cases we should be aware of here? Testing what happens when there are 2 subscriptions to `useWatchBlockNumber` seems like a good test case.

Whoops, not sure how this console.log got there. WIll check

Let's move to PR to discuss this, yes there's one test case to test. I'll describe there in a sec

**Comment by Yuripetusko** [comment]
> @Yuripetusko @acoutts I just tested this branch with instructions above and I can confirm there is only 1 web socket being created.
> 
> I don't see any easier way to handle this. Only kind of strange this is that when I print the result inside of use effect, it will print a function printed first, then `undefined`. Given
> 
> ```
>   useEffect(() => {
>     console.log('inside use effect')
>     console.log(subscription.current)
>     return () => {
>       subscription.current?.()
>       subscription.current = undefined
>     }
>   }, [])
> ```
> 
> I see this printed in the network console:
> 
> ![image](https://private-user-images.githubusercontent.com/16677991/311846460-e0bbd1e4-77e4-4749-82df-6fa1a532457a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxODc5NDEsIm5iZiI6MTcxMDE4NzY0MSwicGF0aCI6Ii8xNjY3Nzk5MS8zMTE4NDY0NjAtZTBiYmQxZTQtNzdlNC00NzQ5LTgyZGYtNmZhMWE1MzI0NTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDIwMDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNTJmMjZiNDBjODgxNTM0MGYyNzIzYzIzNDQ1ZDkxNWFmNGYyNTNlZmU5MGY0NDA2OWE3NjcyODNhODk3OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FfqsMsp8__-XUFRdNgkVRblsigLS8kywu-_7WvCj-Ik)
> 
> Are there any obvious edge cases we should be aware of here? Testing what happens when there are 2 subscriptions to `useWatchBlockNumber` seems like a good test case.

I have no idea how you got this console.log, I removed it when I commited the code lol. Unless you checked out the old commit? 🤔  I don't see other explanation hmm

**Comment by Yuripetusko** [comment]
Ah it's your code. Funny because I had exact same console.log message lol. I think the reason for this is that in dev mode react runs useEffect twice to help devs catch issues early (which I think is a stupid idea)

**Comment by wkyleg** [comment]
I just tried wrapping with `observe` in Viem, I'm not sure best practices for testing but I pushed this fix for reference 

https://github.com/wevm/viem/pull/1929

**Comment by Yuripetusko** [comment]
Nice! i'll try to update viem once it's released and re-test with that version

**Comment by jxom** [comment]
Fixed via Viem.

**Comment by Yuripetusko** [comment]
I think the issue is still there, but need to create a unit test that checks for number of subscriptions when using this hook. Will try to do towards the end of the week if I have time, but adding this here just for the reference or in case someone else will try to write a test first
