### ISSUE TITLE
Request expired issue with walletconnect

### ISSUE THREAD

**Issue by caotrongtin99** [wevm/wagmi#3711]
### Describe the bug

**Hi @tmm @glitch-txs 

I am developing a dApp using Next.js and wagmi v2. When I connect dApp to Metamask mobile wallet through walletconnect, and then perform a write method, I don't sign immediately and wait for 5-10', the dApp will throw "Request expired. Please try again". I recognize that the error is from walletconnect (https://github.com/WalletConnect/walletconnect-monorepo/issues/4181). and maybe they have fixed the error in this [PR](https://github.com/WalletConnect/walletconnect-monorepo/pull/4159). so I wonder if it is fixed in the latest wagmi version**

### Link to Minimal Reproducible Example

https://codesandbox.io/p/github/caotrongtin99/wagmi-walletconnect-reproduce/main?workspaceId=f7c409ef-eb1e-44a2-a4ba-2239de2a5015

### Steps To Reproduce

1. Open the codesandbox, click **walletconnect**, open Metamask mobile then scan the QR code to login
2. Switch chain to Sepolia network on Metamask mobile (because i suppose to interact with sepolia smart contract)
3. Click Write button and wait for a while (5-10')
4. We will see un error like that
`An unknown RPC error occurred. Request Arguments: chain: undefined (id: 11155111) from: 0x5D5701FD2564AC01FB1273158B3CD4AFD0bB7339 to: 0x7069C635d6fCd1C3D0cd9b563CDC6373e06052ee value: 0 ETH data: 0x095ea7b30000000000000000000000000ad482cc99e68da90ce994a1619fdcca0966319c0000000000000000000000000000000000000000000000000000000000000000 Details: Request expired. Please try again. Version: viem@2.8.9`

### Wagmi Version

2.5.7

### Viem Version

2.8.9

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by jxom** [comment]
Should be fixed via https://github.com/wevm/wagmi/commit/1c1fee6ab8f01f7734ac6ce05093fa8e388beb3e.

**Comment by caotrongtin99** [comment]
hi @jxom , i just upgraded to the latest version, but the error is still there, u can check on [my Codesandbox ](https://codesandbox.io/p/github/caotrongtin99/wagmi-walletconnect-reproduce/main?workspaceId=f7c409ef-eb1e-44a2-a4ba-2239de2a5015). Thanks

**Comment by caotrongtin99** [comment]
hi team, can I reopen the issue? @jxom

**Comment by jxom** [comment]
Not sure if this is really a Wagmi issue. Best to get in touch where the error is occuring (WalletConnect or MetaMask).
